### ISSUE TITLE
ui not showing up

### ISSUE THREAD

**Issue by GEOFSUSER1** [Qantas94Heavy/autopilot-pp#10]
I downloaded Ap++ using tampermonkey and when i install and run the plugin the new autopilot buttons appear but with no labels of what they are and when i try to use the autopilot feature it will not work. Any suggestions?

**Comment by Qantas94Heavy** [comment]
Hi, could you please provide a screenshot of what this looks like?

**Comment by GEOFSUSER1** [comment]
I redownloaded the extension and it seems to be working for me now.

**Comment by Qantas94Heavy** [comment]
Glad to hear that AP++ is working for you now!
