### ISSUE TITLE
Plane starts falling after reaching cruise altitude

### ISSUE THREAD

**Issue by MioHaq** [Qantas94Heavy/autopilot-pp#12]
Hi! I have a bug with autopilot++. The autopilot works perfectly until reaching cruise altitude. It starts levelling off OK, but when it has completely reached the altitude set in the navigation tab, it stalls the plane. Now even when the plane is in full throttle, it goes straight down. After restarting the simulation the plane is stuck in the air with no engine power. (So it doesn't descend nor ascend, nor does it turn).

Technical information:
-Windows 10 build 17134 (64-bit)
-Chrome 69.0.3497.100 (official 64-bit build)
-Autopilot++ 0.11.2
-Tampermonkey 4.7
-I use FMC-RequireJS plugin as well, but this problem occurred even with FMC disabled.

If you want any additional information (or if you didn't understand my explanation of the problem) just ask for more information!

**Comment by Qantas94Heavy** [comment]
Hello, could you please provide a screenshot of the aircraft at cruising level before the issue occurs? Thanks!

**Comment by MioHaq** [comment]
![screenshot 30](https://user-images.githubusercontent.com/27084888/46571180-22fc8380-c979-11e8-9ffc-b03a262aa5a4.png)
![screenshot 39](https://user-images.githubusercontent.com/27084888/46571188-4b847d80-c979-11e8-9ec9-3ace5e51b06d.png)

**Comment by Qantas94Heavy** [comment]
Hello, could you please try another aircraft at the same conditions and see if the issue also occurs? This will help to narrow down the problem. If it does happen, please make a screenshot **before** the issue happens.

**Comment by mm-git01** [comment]
Hey,i have faced similar problem. with the auto pilot.

**Comment by mm-git01** [comment]
@Qantas94Heavy @MioHaq apparently this is a in game model issue,the B777,B757,B767,A350 models have problems, everyone has reported this on the google forum.

**Comment by Qantas94Heavy** [comment]
@Pac23 those are all community contributed aircraft. It appears this is an issue with the aircraft models, so only the aircraft creator can fix this.
