### ISSUE TITLE
Doesn't load in new GeoFS version

### ISSUE THREAD

**Issue by PH-KDX** [Qantas94Heavy/autopilot-pp#14]
Hi Quantas94Heavy,
AP++ doesn't load on the new version of GeoFS, as the new autopilot isn't in the NAV panel but in a transparent overhead panel. Could you please fix this?
Thanks,
PH-KDX

**Comment by Qantas94Heavy** [comment]
Hi there, I am aware of the issue and a fix will be out as soon as it is ready.

**Comment by xtassin** [comment]
Hi,

I just restored the legacy autopilot UI and tested it successfully with the original scripts for AP++ and FMC.

Only issue so far is that when AP++ script is running, the new autopilot UI will not be functional.

**Comment by PH-KDX** [comment]
Perfect, thanks
