### ISSUE TITLE
autopilot doesn't turn on

### ISSUE THREAD

**Issue by Boeing74** [Qantas94Heavy/autopilot-pp#15]

**Comment by EricB01** [comment]
I cant turn on autopilot too does your make a beeping sound?

**Comment by Boeing74** [comment]
no

**Comment by EricB01** [comment]
Boeing, Do you know why mines is beeping?

**Comment by Boeing74** [comment]
no

**Comment by aBoredDev** [comment]
@Boeing74 @EricB01 In order for the AP to turn on, you must be above a certain altitude.  I think it's 1000ft, though I am not certain.
