### ISSUE TITLE
Problem With AP++

### ISSUE THREAD

**Issue by besanger321** [Qantas94Heavy/autopilot-pp#18]
Hello Qantas94heavy I know that since the last update of geofs the autopilot has changed and the fact that we can no longer use your extension I still wanted to know if somehow we could use your extension

**Comment by nicolas377** [comment]
Replace the header with this:
// ==UserScript==
// @name Autopilot++ for GeoFS
// @description Take the autopilot experience to the next level with new features!
// @author Qantas 94 Heavy
// @namespace GEFS-Plugins
// @match http://www.geo-fs.com/geofs.php*
// @match http://www.geo-fs.com/geofs.php*
// @match https://www.geo-fs.com/geofs.php*
// @match https://www.geo-fs.com/geofs.php*
// @run-at document-end
// @version 0.11.2
// @grant none
// ==/UserScript==

/**
 * @license almond 0.3.3 Copyright jQuery Foundation and other contributors.
 * Released under MIT license, http://github.com/requirejs/almond/LICENSE
 */

/*!
 * Knockout JavaScript library v3.4.2
 * (c) The Knockout.js team - http://knockoutjs.com/
 * License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

/*!
 * @license Copyright (c) Karl Cheng 2013-17
 * Licensed under the GNU General Public Licence, version 3 or later.
 * See the LICENSE.md file for details.
 */

**Comment by flight863** [comment]
This only turns off regular AP off for me

**Comment by Qantas94Heavy** [comment]
Have tested latest release with Tampermonkey and it seems to load fine.
