### ISSUE TITLE
Autopilot++ Occasionally Disengages on its own

### ISSUE THREAD

**Issue by shantanubdas2002** [Qantas94Heavy/autopilot-pp#3]
First of all, I love Autopilot++ so much and I feel its very useful. But there is a small bug I face with Autopilot++ where it disengages on its own. Sometimes while I'm flying my AP++ disengages on its own causing my plane in the game to descend very slowly and hit the ground.

I also face this problem when I refresh my page and I insert my AP settings again. Sometimes when my plane crashes, I refresh my page while in the air and I have to reinsert all my AP settings and engage it. However it disengages, which causes my plane to be manually controllable even though engaged and also causes my plane to crash. Any advice?

QANTAS PLEASE FIX IT!

**Comment by Qantas94Heavy** [comment]
Hi, do you have wind on? Please test with wind disabled and see if the disconnects continue.

Sometimes having wind on can cause spurious stall warnings, which will cause the autopilot to disconnect.

**Comment by shantanubdas2002** [comment]
LOL I normally keep wind on but this doesnt happen often. The problem is sometimes I refresh the game and when I reinput AP settings my plane stalls anyway which causes AP to disconnect. Just please disable Autopilot disabling while stalling.

**Comment by Qantas94Heavy** [comment]
This is done to simulate real life behaviour of autopilots, as a stall is meant to require immediate corrective action by the pilot.

To avoid this, only activate the autopilot once the aircraft is level and at sufficient speed to avoid stalling.
