### ISSUE TITLE
AP++ Does Not Work (Different From Other Issues)

### ISSUE THREAD

**Issue by Gamer1029384756** [Qantas94Heavy/autopilot-pp#32]
The AP++ does not work. It loads but when I press 'A', it uses the original autopilot. If I press the 'disengaged' button and tick the parameters, it looks normal but it does not work and I can use my mouse which shouldn't be possible.

It usually gets fixed if I reload GeoFS but not in this case. I use the latest version. I don't think it's because of the AP++ itself because it just suddenly stopped working.

**Comment by Gamer1029384756** [comment]
It usually gets fixed if I reload GeoFS but not in this case. I use the latest version. I don't think it's because of the AP++ itself because it just suddenly stopped working.

**Comment by Gamer1029384756** [comment]
The fix is to change the aircraft, not reload the site.

**Comment by krunchiekrunch** [comment]
If you change to another aircraft and change back, it's fixes itself
