### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by RhysV29** [Qantas94Heavy/autopilot-pp#4]
I use Windows 10 and when I change the code to java script (Tampermonkey) It will not load up

**Comment by Qantas94Heavy** [comment]
Hi, I'm able to run Autopilot++ with Google Chrome and Tampermonkey on Windows 10. Could you describe your problem in more detail?

**Comment by RhysV29** [comment]
Well, the autopilot worked in the end for me, but now I'm trying to install
the FMC for Geo-FS, and it won't work. I can't drag the code into
Tampermonkey.

**Comment by Qantas94Heavy** [comment]
Okay, you'll have to ask the developers of the FMC, as that isn't an Autopilot++ issue.
