### ISSUE TITLE
Fatal Plugin Error in Geo-Fs

### ISSUE THREAD

**Issue by SLAMOVNIK989** [Qantas94Heavy/autopilot-pp#7]
No part of plugin is working: Autopilot enabling causing High-G Turns and elevator control disengage, causing airplane stall and crash into terrain/water.
Proof: 
![snimka obrazovky 59](https://user-images.githubusercontent.com/30974571/29248638-539521a6-801d-11e7-8201-326c7c0946c8.png)
Signed,
SLAMOVNIK989

**Comment by Qantas94Heavy** [comment]
Hi, testing this on a normal flight, I cannot reproduce this on the A380.

Not related, but as a side note it seems that 295 KIAS is too fast at cruising altitudes. It should be about Mach 0.85 or about 250 KIAS.
