### ISSUE TITLE
Autopilot++ Text Fields Messed Up

### ISSUE THREAD

**Issue by shantanubdas2002** [Qantas94Heavy/autopilot-pp#8]
![ap issue](https://user-images.githubusercontent.com/29405098/34192725-4183bc14-e569-11e7-8690-aef0f2099534.JPG)

Based on the screenshot above, many people (not just me) suddenly faced an issue yesterday evening where the Autopilot is unusable. Basically all the text fields are all over the place and the AP is not functional. How did it suddenly happen? - Out of curiosity? Any quick fix is possible? I've planned a group flight for the next three days so please try to investigate this issue and fix quickly - if you can. Sorry for the inconvenience.

**Comment by CarLover014** [comment]
If GeoFS had a version update, the Autopilot might just need to be supported for that version

**Comment by shantanubdas2002** [comment]
@CarLover014 Did it have a version update? I'm not very sure about that. So AP++ is no longer supported with the newer version? @Qantas94Heavy Please fix.

**Comment by Qantas94Heavy** [comment]
Investigating -- will release an update shortly.

**Comment by wiktor2034** [comment]
What's with update?

**Comment by Qantas94Heavy** [comment]
This issue has now been fixed in the latest update v0.11.1.

**Comment by Mushr00m2010** [comment]
i also have this right now suddenly it was f###ed 11-12-2024

**Comment by TheAnonym3000** [comment]
Appereared again

**Comment by FlorianT-FR** [comment]
Hello,
I found the problem and made a pull request on January the 3rd. Hovever, @Qantas94Heavy hasn't any activity on GitHub since October 2024, and I have no comment in the pull request.
The last update was 4 years ago, I think that the project is abandoned.
